version: '3.7'

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "31337:9000"
        volumes: 
            - ./source:/usr/src/app
        environment: 
            - SSTI_LEVEL=2
          