version: '3.7'
services: 
    web:
        build: 
            context: .
            dockerfile: web20.dockerfile
        ports: 
            - '31000:80'
        stdin_open: true
        tty: true

        volumes: 
            - ./source:/usr/share/nginx/html
            - ./logs:/var/log/nginx
