version: '3.7'

services: 
    web:
        build: 
            context: .
            dockerfile: web150.dockerfile
        ports: 
            - '30071:80'
        stdin_open: true
        tty: true
        volumes: 
            - ./source:/var/www/html
            - ./logs:/var/log/apache2