version: "3.7"

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        ports: 
            - '30072:80'
        volumes: 
            - ./source:/var/www/html
            - ./flag:/flag
            - ./logs:/var/log/apache2