version: '3.7'

services: 
    web:
        container_name: 'guess_the_code_challenge'
        image: nginx:latest
        ports: 
            - '31010:80'
        volumes: 
            - ./source:/app_source
            - ./challenge.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - guess_the_code-network
    php:
        image: php:fpm
        volumes: 
            - ./source:/app_source

        networks:
            - guess_the_code-network
    

networks:
    guess_the_code-network:
        driver: bridge


